"""initial migration

Revision ID: 333108e9fc9f
Revises: 
Create Date: 2018-05-17 11:37:58.700645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333108e9fc9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('schools__music')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools__music',
    sa.Column('schools_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('addr', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('schools_id', name='schools__music_pkey')
    )
    op.create_table('students',
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('addr', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('student_id', name='students_pkey')
    )
    # ### end Alembic commands ###
